[2017-11-08 15:38:49] DEBUG [django.db.backends:90] (0.002) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
[2017-11-08 15:38:49] DEBUG [django.db.backends:90] (0.001) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
[2017-11-08 15:39:10] DEBUG [django.template:929] Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "E:\Proyecto2017\translipsur\ve_translipsur\lib\site-packages\django\core\handlers\exception.py", line 39, in inner
    response = get_response(request)
  File "E:\Proyecto2017\translipsur\ve_translipsur\lib\site-packages\django\core\handlers\base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "E:\Proyecto2017\translipsur\ve_translipsur\lib\site-packages\django\core\handlers\base.py", line 172, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "E:\Proyecto2017\translipsur\ve_translipsur\lib\site-packages\django\urls\resolvers.py", line 300, in resolve
    raise Resolver404({'tried': tried, 'path': new_path})
django.urls.exceptions.Resolver404: {'tried': [[<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>], [<RegexURLResolver <module 'django.contrib.admindocs.urls' from 'E:\\Proyecto2017\\translipsur\\ve_translipsur\\lib\\site-packages\\django\\contrib\\admindocs\\urls.py'> (None:None) ^admin/doc/>], [<RegexURLResolver <module 'rest_framework.urls' from 'E:\\Proyecto2017\\translipsur\\ve_translipsur\\lib\\site-packages\\rest_framework\\urls.py'> (rest_framework:rest_framework) ^api-auth/>], [<RegexURLResolver <module 'oauth2_provider.urls' from 'E:\\Proyecto2017\\translipsur\\ve_translipsur\\lib\\site-packages\\oauth2_provider\\urls.py'> (None:oauth2_provider) ^o/>], [<RegexURLResolver <module 'translipsur_service_apps.auths_api.urls' from 'E:\\Proyecto2017\\translipsur\\translipsur_service\\translipsur_service_apps\\auths_api\\urls.py'> (None:None) ^api/auths/>], [<RegexURLResolver <module 'translipsur_service_apps.repositorio_api.urls' from 'E:\\Proyecto2017\\translipsur\\translipsur_service\\translipsur_service_apps\\repositorio_api\\urls.py'> (None:None) ^api/repositorio/>]], 'path': ''}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Proyecto2017\translipsur\ve_translipsur\lib\site-packages\django\template\base.py", line 885, in _resolve_lookup
    current = current[bit]
TypeError: 'RegexURLResolver' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Proyecto2017\translipsur\ve_translipsur\lib\site-packages\django\template\base.py", line 893, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'RegexURLResolver' object has no attribute 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Proyecto2017\translipsur\ve_translipsur\lib\site-packages\django\template\base.py", line 900, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Proyecto2017\translipsur\ve_translipsur\lib\site-packages\django\template\base.py", line 907, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [name] in '<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>'
[2017-11-08 15:39:10] DEBUG [django.template:929] Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "E:\Proyecto2017\translipsur\ve_translipsur\lib\site-packages\django\core\handlers\exception.py", line 39, in inner
    response = get_response(request)
  File "E:\Proyecto2017\translipsur\ve_translipsur\lib\site-packages\django\core\handlers\base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "E:\Proyecto2017\translipsur\ve_translipsur\lib\site-packages\django\core\handlers\base.py", line 172, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "E:\Proyecto2017\translipsur\ve_translipsur\lib\site-packages\django\urls\resolvers.py", line 300, in resolve
    raise Resolver404({'tried': tried, 'path': new_path})
django.urls.exceptions.Resolver404: {'tried': [[<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>], [<RegexURLResolver <module 'django.contrib.admindocs.urls' from 'E:\\Proyecto2017\\translipsur\\ve_translipsur\\lib\\site-packages\\django\\contrib\\admindocs\\urls.py'> (None:None) ^admin/doc/>], [<RegexURLResolver <module 'rest_framework.urls' from 'E:\\Proyecto2017\\translipsur\\ve_translipsur\\lib\\site-packages\\rest_framework\\urls.py'> (rest_framework:rest_framework) ^api-auth/>], [<RegexURLResolver <module 'oauth2_provider.urls' from 'E:\\Proyecto2017\\translipsur\\ve_translipsur\\lib\\site-packages\\oauth2_provider\\urls.py'> (None:oauth2_provider) ^o/>], [<RegexURLResolver <module 'translipsur_service_apps.auths_api.urls' from 'E:\\Proyecto2017\\translipsur\\translipsur_service\\translipsur_service_apps\\auths_api\\urls.py'> (None:None) ^api/auths/>], [<RegexURLResolver <module 'translipsur_service_apps.repositorio_api.urls' from 'E:\\Proyecto2017\\translipsur\\translipsur_service\\translipsur_service_apps\\repositorio_api\\urls.py'> (None:None) ^api/repositorio/>]], 'path': ''}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Proyecto2017\translipsur\ve_translipsur\lib\site-packages\django\template\base.py", line 885, in _resolve_lookup
    current = current[bit]
TypeError: 'RegexURLResolver' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Proyecto2017\translipsur\ve_translipsur\lib\site-packages\django\template\base.py", line 893, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'RegexURLResolver' object has no attribute 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Proyecto2017\translipsur\ve_translipsur\lib\site-packages\django\template\base.py", line 900, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Proyecto2017\translipsur\ve_translipsur\lib\site-packages\django\template\base.py", line 907, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [name] in "<RegexURLResolver <module 'django.contrib.admindocs.urls' from 'E:\\\\Proyecto2017\\\\translipsur\\\\ve_translipsur\\\\lib\\\\site-packages\\\\django\\\\contrib\\\\admindocs\\\\urls.py'> (None:None) ^admin/doc/>"
[2017-11-08 15:39:10] DEBUG [django.template:929] Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "E:\Proyecto2017\translipsur\ve_translipsur\lib\site-packages\django\core\handlers\exception.py", line 39, in inner
    response = get_response(request)
  File "E:\Proyecto2017\translipsur\ve_translipsur\lib\site-packages\django\core\handlers\base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "E:\Proyecto2017\translipsur\ve_translipsur\lib\site-packages\django\core\handlers\base.py", line 172, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "E:\Proyecto2017\translipsur\ve_translipsur\lib\site-packages\django\urls\resolvers.py", line 300, in resolve
    raise Resolver404({'tried': tried, 'path': new_path})
django.urls.exceptions.Resolver404: {'tried': [[<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>], [<RegexURLResolver <module 'django.contrib.admindocs.urls' from 'E:\\Proyecto2017\\translipsur\\ve_translipsur\\lib\\site-packages\\django\\contrib\\admindocs\\urls.py'> (None:None) ^admin/doc/>], [<RegexURLResolver <module 'rest_framework.urls' from 'E:\\Proyecto2017\\translipsur\\ve_translipsur\\lib\\site-packages\\rest_framework\\urls.py'> (rest_framework:rest_framework) ^api-auth/>], [<RegexURLResolver <module 'oauth2_provider.urls' from 'E:\\Proyecto2017\\translipsur\\ve_translipsur\\lib\\site-packages\\oauth2_provider\\urls.py'> (None:oauth2_provider) ^o/>], [<RegexURLResolver <module 'translipsur_service_apps.auths_api.urls' from 'E:\\Proyecto2017\\translipsur\\translipsur_service\\translipsur_service_apps\\auths_api\\urls.py'> (None:None) ^api/auths/>], [<RegexURLResolver <module 'translipsur_service_apps.repositorio_api.urls' from 'E:\\Proyecto2017\\translipsur\\translipsur_service\\translipsur_service_apps\\repositorio_api\\urls.py'> (None:None) ^api/repositorio/>]], 'path': ''}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Proyecto2017\translipsur\ve_translipsur\lib\site-packages\django\template\base.py", line 885, in _resolve_lookup
    current = current[bit]
TypeError: 'RegexURLResolver' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Proyecto2017\translipsur\ve_translipsur\lib\site-packages\django\template\base.py", line 893, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'RegexURLResolver' object has no attribute 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Proyecto2017\translipsur\ve_translipsur\lib\site-packages\django\template\base.py", line 900, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Proyecto2017\translipsur\ve_translipsur\lib\site-packages\django\template\base.py", line 907, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [name] in "<RegexURLResolver <module 'rest_framework.urls' from 'E:\\\\Proyecto2017\\\\translipsur\\\\ve_translipsur\\\\lib\\\\site-packages\\\\rest_framework\\\\urls.py'> (rest_framework:rest_framework) ^api-auth/>"
[2017-11-08 15:39:10] DEBUG [django.template:929] Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "E:\Proyecto2017\translipsur\ve_translipsur\lib\site-packages\django\core\handlers\exception.py", line 39, in inner
    response = get_response(request)
  File "E:\Proyecto2017\translipsur\ve_translipsur\lib\site-packages\django\core\handlers\base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "E:\Proyecto2017\translipsur\ve_translipsur\lib\site-packages\django\core\handlers\base.py", line 172, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "E:\Proyecto2017\translipsur\ve_translipsur\lib\site-packages\django\urls\resolvers.py", line 300, in resolve
    raise Resolver404({'tried': tried, 'path': new_path})
django.urls.exceptions.Resolver404: {'tried': [[<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>], [<RegexURLResolver <module 'django.contrib.admindocs.urls' from 'E:\\Proyecto2017\\translipsur\\ve_translipsur\\lib\\site-packages\\django\\contrib\\admindocs\\urls.py'> (None:None) ^admin/doc/>], [<RegexURLResolver <module 'rest_framework.urls' from 'E:\\Proyecto2017\\translipsur\\ve_translipsur\\lib\\site-packages\\rest_framework\\urls.py'> (rest_framework:rest_framework) ^api-auth/>], [<RegexURLResolver <module 'oauth2_provider.urls' from 'E:\\Proyecto2017\\translipsur\\ve_translipsur\\lib\\site-packages\\oauth2_provider\\urls.py'> (None:oauth2_provider) ^o/>], [<RegexURLResolver <module 'translipsur_service_apps.auths_api.urls' from 'E:\\Proyecto2017\\translipsur\\translipsur_service\\translipsur_service_apps\\auths_api\\urls.py'> (None:None) ^api/auths/>], [<RegexURLResolver <module 'translipsur_service_apps.repositorio_api.urls' from 'E:\\Proyecto2017\\translipsur\\translipsur_service\\translipsur_service_apps\\repositorio_api\\urls.py'> (None:None) ^api/repositorio/>]], 'path': ''}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Proyecto2017\translipsur\ve_translipsur\lib\site-packages\django\template\base.py", line 885, in _resolve_lookup
    current = current[bit]
TypeError: 'RegexURLResolver' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Proyecto2017\translipsur\ve_translipsur\lib\site-packages\django\template\base.py", line 893, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'RegexURLResolver' object has no attribute 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Proyecto2017\translipsur\ve_translipsur\lib\site-packages\django\template\base.py", line 900, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Proyecto2017\translipsur\ve_translipsur\lib\site-packages\django\template\base.py", line 907, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [name] in "<RegexURLResolver <module 'oauth2_provider.urls' from 'E:\\\\Proyecto2017\\\\translipsur\\\\ve_translipsur\\\\lib\\\\site-packages\\\\oauth2_provider\\\\urls.py'> (None:oauth2_provider) ^o/>"
[2017-11-08 15:39:10] DEBUG [django.template:929] Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "E:\Proyecto2017\translipsur\ve_translipsur\lib\site-packages\django\core\handlers\exception.py", line 39, in inner
    response = get_response(request)
  File "E:\Proyecto2017\translipsur\ve_translipsur\lib\site-packages\django\core\handlers\base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "E:\Proyecto2017\translipsur\ve_translipsur\lib\site-packages\django\core\handlers\base.py", line 172, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "E:\Proyecto2017\translipsur\ve_translipsur\lib\site-packages\django\urls\resolvers.py", line 300, in resolve
    raise Resolver404({'tried': tried, 'path': new_path})
django.urls.exceptions.Resolver404: {'tried': [[<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>], [<RegexURLResolver <module 'django.contrib.admindocs.urls' from 'E:\\Proyecto2017\\translipsur\\ve_translipsur\\lib\\site-packages\\django\\contrib\\admindocs\\urls.py'> (None:None) ^admin/doc/>], [<RegexURLResolver <module 'rest_framework.urls' from 'E:\\Proyecto2017\\translipsur\\ve_translipsur\\lib\\site-packages\\rest_framework\\urls.py'> (rest_framework:rest_framework) ^api-auth/>], [<RegexURLResolver <module 'oauth2_provider.urls' from 'E:\\Proyecto2017\\translipsur\\ve_translipsur\\lib\\site-packages\\oauth2_provider\\urls.py'> (None:oauth2_provider) ^o/>], [<RegexURLResolver <module 'translipsur_service_apps.auths_api.urls' from 'E:\\Proyecto2017\\translipsur\\translipsur_service\\translipsur_service_apps\\auths_api\\urls.py'> (None:None) ^api/auths/>], [<RegexURLResolver <module 'translipsur_service_apps.repositorio_api.urls' from 'E:\\Proyecto2017\\translipsur\\translipsur_service\\translipsur_service_apps\\repositorio_api\\urls.py'> (None:None) ^api/repositorio/>]], 'path': ''}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Proyecto2017\translipsur\ve_translipsur\lib\site-packages\django\template\base.py", line 885, in _resolve_lookup
    current = current[bit]
TypeError: 'RegexURLResolver' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Proyecto2017\translipsur\ve_translipsur\lib\site-packages\django\template\base.py", line 893, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'RegexURLResolver' object has no attribute 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Proyecto2017\translipsur\ve_translipsur\lib\site-packages\django\template\base.py", line 900, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Proyecto2017\translipsur\ve_translipsur\lib\site-packages\django\template\base.py", line 907, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [name] in "<RegexURLResolver <module 'translipsur_service_apps.auths_api.urls' from 'E:\\\\Proyecto2017\\\\translipsur\\\\translipsur_service\\\\translipsur_service_apps\\\\auths_api\\\\urls.py'> (None:None) ^api/auths/>"
[2017-11-08 15:39:10] DEBUG [django.template:929] Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "E:\Proyecto2017\translipsur\ve_translipsur\lib\site-packages\django\core\handlers\exception.py", line 39, in inner
    response = get_response(request)
  File "E:\Proyecto2017\translipsur\ve_translipsur\lib\site-packages\django\core\handlers\base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "E:\Proyecto2017\translipsur\ve_translipsur\lib\site-packages\django\core\handlers\base.py", line 172, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "E:\Proyecto2017\translipsur\ve_translipsur\lib\site-packages\django\urls\resolvers.py", line 300, in resolve
    raise Resolver404({'tried': tried, 'path': new_path})
django.urls.exceptions.Resolver404: {'tried': [[<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>], [<RegexURLResolver <module 'django.contrib.admindocs.urls' from 'E:\\Proyecto2017\\translipsur\\ve_translipsur\\lib\\site-packages\\django\\contrib\\admindocs\\urls.py'> (None:None) ^admin/doc/>], [<RegexURLResolver <module 'rest_framework.urls' from 'E:\\Proyecto2017\\translipsur\\ve_translipsur\\lib\\site-packages\\rest_framework\\urls.py'> (rest_framework:rest_framework) ^api-auth/>], [<RegexURLResolver <module 'oauth2_provider.urls' from 'E:\\Proyecto2017\\translipsur\\ve_translipsur\\lib\\site-packages\\oauth2_provider\\urls.py'> (None:oauth2_provider) ^o/>], [<RegexURLResolver <module 'translipsur_service_apps.auths_api.urls' from 'E:\\Proyecto2017\\translipsur\\translipsur_service\\translipsur_service_apps\\auths_api\\urls.py'> (None:None) ^api/auths/>], [<RegexURLResolver <module 'translipsur_service_apps.repositorio_api.urls' from 'E:\\Proyecto2017\\translipsur\\translipsur_service\\translipsur_service_apps\\repositorio_api\\urls.py'> (None:None) ^api/repositorio/>]], 'path': ''}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Proyecto2017\translipsur\ve_translipsur\lib\site-packages\django\template\base.py", line 885, in _resolve_lookup
    current = current[bit]
TypeError: 'RegexURLResolver' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Proyecto2017\translipsur\ve_translipsur\lib\site-packages\django\template\base.py", line 893, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'RegexURLResolver' object has no attribute 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Proyecto2017\translipsur\ve_translipsur\lib\site-packages\django\template\base.py", line 900, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Proyecto2017\translipsur\ve_translipsur\lib\site-packages\django\template\base.py", line 907, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [name] in "<RegexURLResolver <module 'translipsur_service_apps.repositorio_api.urls' from 'E:\\\\Proyecto2017\\\\translipsur\\\\translipsur_service\\\\translipsur_service_apps\\\\repositorio_api\\\\urls.py'> (None:None) ^api/repositorio/>"
[2017-11-08 15:39:10] WARNING [django.request:152] Not Found: /
[2017-11-08 15:39:10] WARNING [django.server:131] "GET / HTTP/1.1" 404 2465
[2017-11-08 15:39:10] DEBUG [django.template:929] Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "E:\Proyecto2017\translipsur\ve_translipsur\lib\site-packages\django\core\handlers\exception.py", line 39, in inner
    response = get_response(request)
  File "E:\Proyecto2017\translipsur\ve_translipsur\lib\site-packages\django\core\handlers\base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "E:\Proyecto2017\translipsur\ve_translipsur\lib\site-packages\django\core\handlers\base.py", line 172, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "E:\Proyecto2017\translipsur\ve_translipsur\lib\site-packages\django\urls\resolvers.py", line 300, in resolve
    raise Resolver404({'tried': tried, 'path': new_path})
django.urls.exceptions.Resolver404: {'tried': [[<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>], [<RegexURLResolver <module 'django.contrib.admindocs.urls' from 'E:\\Proyecto2017\\translipsur\\ve_translipsur\\lib\\site-packages\\django\\contrib\\admindocs\\urls.py'> (None:None) ^admin/doc/>], [<RegexURLResolver <module 'rest_framework.urls' from 'E:\\Proyecto2017\\translipsur\\ve_translipsur\\lib\\site-packages\\rest_framework\\urls.py'> (rest_framework:rest_framework) ^api-auth/>], [<RegexURLResolver <module 'oauth2_provider.urls' from 'E:\\Proyecto2017\\translipsur\\ve_translipsur\\lib\\site-packages\\oauth2_provider\\urls.py'> (None:oauth2_provider) ^o/>], [<RegexURLResolver <module 'translipsur_service_apps.auths_api.urls' from 'E:\\Proyecto2017\\translipsur\\translipsur_service\\translipsur_service_apps\\auths_api\\urls.py'> (None:None) ^api/auths/>], [<RegexURLResolver <module 'translipsur_service_apps.repositorio_api.urls' from 'E:\\Proyecto2017\\translipsur\\translipsur_service\\translipsur_service_apps\\repositorio_api\\urls.py'> (None:None) ^api/repositorio/>]], 'path': 'favicon.ico'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Proyecto2017\translipsur\ve_translipsur\lib\site-packages\django\template\base.py", line 885, in _resolve_lookup
    current = current[bit]
TypeError: 'RegexURLResolver' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Proyecto2017\translipsur\ve_translipsur\lib\site-packages\django\template\base.py", line 893, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'RegexURLResolver' object has no attribute 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Proyecto2017\translipsur\ve_translipsur\lib\site-packages\django\template\base.py", line 900, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Proyecto2017\translipsur\ve_translipsur\lib\site-packages\django\template\base.py", line 907, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [name] in '<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>'
[2017-11-08 15:39:10] DEBUG [django.template:929] Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "E:\Proyecto2017\translipsur\ve_translipsur\lib\site-packages\django\core\handlers\exception.py", line 39, in inner
    response = get_response(request)
  File "E:\Proyecto2017\translipsur\ve_translipsur\lib\site-packages\django\core\handlers\base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "E:\Proyecto2017\translipsur\ve_translipsur\lib\site-packages\django\core\handlers\base.py", line 172, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "E:\Proyecto2017\translipsur\ve_translipsur\lib\site-packages\django\urls\resolvers.py", line 300, in resolve
    raise Resolver404({'tried': tried, 'path': new_path})
django.urls.exceptions.Resolver404: {'tried': [[<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>], [<RegexURLResolver <module 'django.contrib.admindocs.urls' from 'E:\\Proyecto2017\\translipsur\\ve_translipsur\\lib\\site-packages\\django\\contrib\\admindocs\\urls.py'> (None:None) ^admin/doc/>], [<RegexURLResolver <module 'rest_framework.urls' from 'E:\\Proyecto2017\\translipsur\\ve_translipsur\\lib\\site-packages\\rest_framework\\urls.py'> (rest_framework:rest_framework) ^api-auth/>], [<RegexURLResolver <module 'oauth2_provider.urls' from 'E:\\Proyecto2017\\translipsur\\ve_translipsur\\lib\\site-packages\\oauth2_provider\\urls.py'> (None:oauth2_provider) ^o/>], [<RegexURLResolver <module 'translipsur_service_apps.auths_api.urls' from 'E:\\Proyecto2017\\translipsur\\translipsur_service\\translipsur_service_apps\\auths_api\\urls.py'> (None:None) ^api/auths/>], [<RegexURLResolver <module 'translipsur_service_apps.repositorio_api.urls' from 'E:\\Proyecto2017\\translipsur\\translipsur_service\\translipsur_service_apps\\repositorio_api\\urls.py'> (None:None) ^api/repositorio/>]], 'path': 'favicon.ico'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Proyecto2017\translipsur\ve_translipsur\lib\site-packages\django\template\base.py", line 885, in _resolve_lookup
    current = current[bit]
TypeError: 'RegexURLResolver' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Proyecto2017\translipsur\ve_translipsur\lib\site-packages\django\template\base.py", line 893, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'RegexURLResolver' object has no attribute 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Proyecto2017\translipsur\ve_translipsur\lib\site-packages\django\template\base.py", line 900, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Proyecto2017\translipsur\ve_translipsur\lib\site-packages\django\template\base.py", line 907, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [name] in "<RegexURLResolver <module 'django.contrib.admindocs.urls' from 'E:\\\\Proyecto2017\\\\translipsur\\\\ve_translipsur\\\\lib\\\\site-packages\\\\django\\\\contrib\\\\admindocs\\\\urls.py'> (None:None) ^admin/doc/>"
[2017-11-08 15:39:10] DEBUG [django.template:929] Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "E:\Proyecto2017\translipsur\ve_translipsur\lib\site-packages\django\core\handlers\exception.py", line 39, in inner
    response = get_response(request)
  File "E:\Proyecto2017\translipsur\ve_translipsur\lib\site-packages\django\core\handlers\base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "E:\Proyecto2017\translipsur\ve_translipsur\lib\site-packages\django\core\handlers\base.py", line 172, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "E:\Proyecto2017\translipsur\ve_translipsur\lib\site-packages\django\urls\resolvers.py", line 300, in resolve
    raise Resolver404({'tried': tried, 'path': new_path})
django.urls.exceptions.Resolver404: {'tried': [[<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>], [<RegexURLResolver <module 'django.contrib.admindocs.urls' from 'E:\\Proyecto2017\\translipsur\\ve_translipsur\\lib\\site-packages\\django\\contrib\\admindocs\\urls.py'> (None:None) ^admin/doc/>], [<RegexURLResolver <module 'rest_framework.urls' from 'E:\\Proyecto2017\\translipsur\\ve_translipsur\\lib\\site-packages\\rest_framework\\urls.py'> (rest_framework:rest_framework) ^api-auth/>], [<RegexURLResolver <module 'oauth2_provider.urls' from 'E:\\Proyecto2017\\translipsur\\ve_translipsur\\lib\\site-packages\\oauth2_provider\\urls.py'> (None:oauth2_provider) ^o/>], [<RegexURLResolver <module 'translipsur_service_apps.auths_api.urls' from 'E:\\Proyecto2017\\translipsur\\translipsur_service\\translipsur_service_apps\\auths_api\\urls.py'> (None:None) ^api/auths/>], [<RegexURLResolver <module 'translipsur_service_apps.repositorio_api.urls' from 'E:\\Proyecto2017\\translipsur\\translipsur_service\\translipsur_service_apps\\repositorio_api\\urls.py'> (None:None) ^api/repositorio/>]], 'path': 'favicon.ico'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Proyecto2017\translipsur\ve_translipsur\lib\site-packages\django\template\base.py", line 885, in _resolve_lookup
    current = current[bit]
TypeError: 'RegexURLResolver' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Proyecto2017\translipsur\ve_translipsur\lib\site-packages\django\template\base.py", line 893, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'RegexURLResolver' object has no attribute 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Proyecto2017\translipsur\ve_translipsur\lib\site-packages\django\template\base.py", line 900, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Proyecto2017\translipsur\ve_translipsur\lib\site-packages\django\template\base.py", line 907, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [name] in "<RegexURLResolver <module 'rest_framework.urls' from 'E:\\\\Proyecto2017\\\\translipsur\\\\ve_translipsur\\\\lib\\\\site-packages\\\\rest_framework\\\\urls.py'> (rest_framework:rest_framework) ^api-auth/>"
[2017-11-08 15:39:10] DEBUG [django.template:929] Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "E:\Proyecto2017\translipsur\ve_translipsur\lib\site-packages\django\core\handlers\exception.py", line 39, in inner
    response = get_response(request)
  File "E:\Proyecto2017\translipsur\ve_translipsur\lib\site-packages\django\core\handlers\base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "E:\Proyecto2017\translipsur\ve_translipsur\lib\site-packages\django\core\handlers\base.py", line 172, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "E:\Proyecto2017\translipsur\ve_translipsur\lib\site-packages\django\urls\resolvers.py", line 300, in resolve
    raise Resolver404({'tried': tried, 'path': new_path})
django.urls.exceptions.Resolver404: {'tried': [[<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>], [<RegexURLResolver <module 'django.contrib.admindocs.urls' from 'E:\\Proyecto2017\\translipsur\\ve_translipsur\\lib\\site-packages\\django\\contrib\\admindocs\\urls.py'> (None:None) ^admin/doc/>], [<RegexURLResolver <module 'rest_framework.urls' from 'E:\\Proyecto2017\\translipsur\\ve_translipsur\\lib\\site-packages\\rest_framework\\urls.py'> (rest_framework:rest_framework) ^api-auth/>], [<RegexURLResolver <module 'oauth2_provider.urls' from 'E:\\Proyecto2017\\translipsur\\ve_translipsur\\lib\\site-packages\\oauth2_provider\\urls.py'> (None:oauth2_provider) ^o/>], [<RegexURLResolver <module 'translipsur_service_apps.auths_api.urls' from 'E:\\Proyecto2017\\translipsur\\translipsur_service\\translipsur_service_apps\\auths_api\\urls.py'> (None:None) ^api/auths/>], [<RegexURLResolver <module 'translipsur_service_apps.repositorio_api.urls' from 'E:\\Proyecto2017\\translipsur\\translipsur_service\\translipsur_service_apps\\repositorio_api\\urls.py'> (None:None) ^api/repositorio/>]], 'path': 'favicon.ico'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Proyecto2017\translipsur\ve_translipsur\lib\site-packages\django\template\base.py", line 885, in _resolve_lookup
    current = current[bit]
TypeError: 'RegexURLResolver' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Proyecto2017\translipsur\ve_translipsur\lib\site-packages\django\template\base.py", line 893, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'RegexURLResolver' object has no attribute 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Proyecto2017\translipsur\ve_translipsur\lib\site-packages\django\template\base.py", line 900, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Proyecto2017\translipsur\ve_translipsur\lib\site-packages\django\template\base.py", line 907, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [name] in "<RegexURLResolver <module 'oauth2_provider.urls' from 'E:\\\\Proyecto2017\\\\translipsur\\\\ve_translipsur\\\\lib\\\\site-packages\\\\oauth2_provider\\\\urls.py'> (None:oauth2_provider) ^o/>"
[2017-11-08 15:39:10] DEBUG [django.template:929] Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "E:\Proyecto2017\translipsur\ve_translipsur\lib\site-packages\django\core\handlers\exception.py", line 39, in inner
    response = get_response(request)
  File "E:\Proyecto2017\translipsur\ve_translipsur\lib\site-packages\django\core\handlers\base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "E:\Proyecto2017\translipsur\ve_translipsur\lib\site-packages\django\core\handlers\base.py", line 172, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "E:\Proyecto2017\translipsur\ve_translipsur\lib\site-packages\django\urls\resolvers.py", line 300, in resolve
    raise Resolver404({'tried': tried, 'path': new_path})
django.urls.exceptions.Resolver404: {'tried': [[<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>], [<RegexURLResolver <module 'django.contrib.admindocs.urls' from 'E:\\Proyecto2017\\translipsur\\ve_translipsur\\lib\\site-packages\\django\\contrib\\admindocs\\urls.py'> (None:None) ^admin/doc/>], [<RegexURLResolver <module 'rest_framework.urls' from 'E:\\Proyecto2017\\translipsur\\ve_translipsur\\lib\\site-packages\\rest_framework\\urls.py'> (rest_framework:rest_framework) ^api-auth/>], [<RegexURLResolver <module 'oauth2_provider.urls' from 'E:\\Proyecto2017\\translipsur\\ve_translipsur\\lib\\site-packages\\oauth2_provider\\urls.py'> (None:oauth2_provider) ^o/>], [<RegexURLResolver <module 'translipsur_service_apps.auths_api.urls' from 'E:\\Proyecto2017\\translipsur\\translipsur_service\\translipsur_service_apps\\auths_api\\urls.py'> (None:None) ^api/auths/>], [<RegexURLResolver <module 'translipsur_service_apps.repositorio_api.urls' from 'E:\\Proyecto2017\\translipsur\\translipsur_service\\translipsur_service_apps\\repositorio_api\\urls.py'> (None:None) ^api/repositorio/>]], 'path': 'favicon.ico'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Proyecto2017\translipsur\ve_translipsur\lib\site-packages\django\template\base.py", line 885, in _resolve_lookup
    current = current[bit]
TypeError: 'RegexURLResolver' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Proyecto2017\translipsur\ve_translipsur\lib\site-packages\django\template\base.py", line 893, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'RegexURLResolver' object has no attribute 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Proyecto2017\translipsur\ve_translipsur\lib\site-packages\django\template\base.py", line 900, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Proyecto2017\translipsur\ve_translipsur\lib\site-packages\django\template\base.py", line 907, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [name] in "<RegexURLResolver <module 'translipsur_service_apps.auths_api.urls' from 'E:\\\\Proyecto2017\\\\translipsur\\\\translipsur_service\\\\translipsur_service_apps\\\\auths_api\\\\urls.py'> (None:None) ^api/auths/>"
[2017-11-08 15:39:10] DEBUG [django.template:929] Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "E:\Proyecto2017\translipsur\ve_translipsur\lib\site-packages\django\core\handlers\exception.py", line 39, in inner
    response = get_response(request)
  File "E:\Proyecto2017\translipsur\ve_translipsur\lib\site-packages\django\core\handlers\base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "E:\Proyecto2017\translipsur\ve_translipsur\lib\site-packages\django\core\handlers\base.py", line 172, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "E:\Proyecto2017\translipsur\ve_translipsur\lib\site-packages\django\urls\resolvers.py", line 300, in resolve
    raise Resolver404({'tried': tried, 'path': new_path})
django.urls.exceptions.Resolver404: {'tried': [[<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>], [<RegexURLResolver <module 'django.contrib.admindocs.urls' from 'E:\\Proyecto2017\\translipsur\\ve_translipsur\\lib\\site-packages\\django\\contrib\\admindocs\\urls.py'> (None:None) ^admin/doc/>], [<RegexURLResolver <module 'rest_framework.urls' from 'E:\\Proyecto2017\\translipsur\\ve_translipsur\\lib\\site-packages\\rest_framework\\urls.py'> (rest_framework:rest_framework) ^api-auth/>], [<RegexURLResolver <module 'oauth2_provider.urls' from 'E:\\Proyecto2017\\translipsur\\ve_translipsur\\lib\\site-packages\\oauth2_provider\\urls.py'> (None:oauth2_provider) ^o/>], [<RegexURLResolver <module 'translipsur_service_apps.auths_api.urls' from 'E:\\Proyecto2017\\translipsur\\translipsur_service\\translipsur_service_apps\\auths_api\\urls.py'> (None:None) ^api/auths/>], [<RegexURLResolver <module 'translipsur_service_apps.repositorio_api.urls' from 'E:\\Proyecto2017\\translipsur\\translipsur_service\\translipsur_service_apps\\repositorio_api\\urls.py'> (None:None) ^api/repositorio/>]], 'path': 'favicon.ico'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Proyecto2017\translipsur\ve_translipsur\lib\site-packages\django\template\base.py", line 885, in _resolve_lookup
    current = current[bit]
TypeError: 'RegexURLResolver' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Proyecto2017\translipsur\ve_translipsur\lib\site-packages\django\template\base.py", line 893, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'RegexURLResolver' object has no attribute 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Proyecto2017\translipsur\ve_translipsur\lib\site-packages\django\template\base.py", line 900, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Proyecto2017\translipsur\ve_translipsur\lib\site-packages\django\template\base.py", line 907, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [name] in "<RegexURLResolver <module 'translipsur_service_apps.repositorio_api.urls' from 'E:\\\\Proyecto2017\\\\translipsur\\\\translipsur_service\\\\translipsur_service_apps\\\\repositorio_api\\\\urls.py'> (None:None) ^api/repositorio/>"
[2017-11-08 15:39:10] WARNING [django.request:152] Not Found: /favicon.ico
[2017-11-08 15:39:10] WARNING [django.server:131] "GET /favicon.ico HTTP/1.1" 404 2498
[2017-11-08 15:39:16] DEBUG [django.db.backends:90] (0.004) SELECT "django_session"."session_key", "django_session"."session_data", "django_session"."expire_date" FROM "django_session" WHERE ("django_session"."session_key" = 'l241eicyrsisp20pz2p7xafbun3a3s1h' AND "django_session"."expire_date" > '2017-11-08 20:39:16.043253'); args=('l241eicyrsisp20pz2p7xafbun3a3s1h', '2017-11-08 20:39:16.043253')
[2017-11-08 15:39:16] DEBUG [django.db.backends:90] (0.000) SELECT "auths_user"."password", "auths_user"."last_login", "auths_user"."is_superuser", "auths_user"."username", "auths_user"."first_name", "auths_user"."last_name", "auths_user"."email", "auths_user"."is_staff", "auths_user"."is_active", "auths_user"."date_joined", "auths_user"."id", "auths_user"."last_hierarchy_id", "auths_user"."last_module_id", "auths_user"."person_id", "auths_user"."updated_at", "auths_user"."registered_by" FROM "auths_user" WHERE "auths_user"."id" = 'aa19e6b5cb564a9c8bdebe3d66e6760e'; args=('aa19e6b5cb564a9c8bdebe3d66e6760e',)
[2017-11-08 15:39:16] DEBUG [django.template:929] Exception while resolving variable 'is_popup' in template 'admin/index.html'.
Traceback (most recent call last):
  File "E:\Proyecto2017\translipsur\ve_translipsur\lib\site-packages\django\template\base.py", line 885, in _resolve_lookup
    current = current[bit]
  File "E:\Proyecto2017\translipsur\ve_translipsur\lib\site-packages\django\template\context.py", line 75, in __getitem__
    raise KeyError(key)
KeyError: 'is_popup'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Proyecto2017\translipsur\ve_translipsur\lib\site-packages\django\template\base.py", line 891, in _resolve_lookup
    if isinstance(current, BaseContext) and getattr(type(current), bit):
AttributeError: type object 'RequestContext' has no attribute 'is_popup'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Proyecto2017\translipsur\ve_translipsur\lib\site-packages\django\template\base.py", line 900, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'is_popup'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Proyecto2017\translipsur\ve_translipsur\lib\site-packages\django\template\base.py", line 907, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [is_popup] in "[{'True': True, 'False': False, 'None': None}, {'csrf_token': <SimpleLazyObject: <function csrf.<locals>._get_val at 0x05375150>>, 'request': <WSGIRequest: GET '/admin/'>, 'user': <SimpleLazyObject: <User: nogami>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x053F7250>, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x047F9E50>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'SUCCESS': 25, 'WARNING': 30, 'ERROR': 40}}, {}, {'site_title': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x03CB0EF0>, 'site_header': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x03CB0F30>, 'site_url': '/', 'has_permission': True, 'available_apps': [{'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x03CC7F10>, 'app_label': 'auth', 'app_url': '/admin/auth/', 'has_module_perms': True, 'models': [{'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x04E32710>, 'object_name': 'Group', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/auth/group/', 'add_url': '/admin/auth/group/add/'}, {'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x04E32CB0>, 'object_name': 'Permission', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/auth/permission/', 'add_url': '/admin/auth/permission/add/'}]}, {'name': 'Auths', 'app_label': 'auths', 'app_url': '/admin/auths/', 'has_module_perms': True, 'models': [{'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x04E32C50>, 'object_name': 'HierarchyType', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/auths/hierarchytype/', 'add_url': '/admin/auths/hierarchytype/add/'}, {'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x04E32B10>, 'object_name': 'Hierarchy', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/auths/hierarchy/', 'add_url': '/admin/auths/hierarchy/add/'}, {'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x04E32E50>, 'object_name': 'Menu', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/auths/menu/', 'add_url': '/admin/auths/menu/add/'}, {'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x04E32EF0>, 'object_name': 'Person', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/auths/person/', 'add_url': '/admin/auths/person/add/'}, {'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x04E32C70>, 'object_name': 'UserHierarchyGroup', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/auths/userhierarchygroup/', 'add_url': '/admin/auths/userhierarchygroup/add/'}, {'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x04E32E70>, 'object_name': 'UserHierarchyPermission', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/auths/userhierarchypermission/', 'add_url': '/admin/auths/userhierarchypermission/add/'}, {'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x0531FDB0>, 'object_name': 'User', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/auths/user/', 'add_url': '/admin/auths/user/add/'}]}, {'name': 'Django OAuth Toolkit', 'app_label': 'oauth2_provider', 'app_url': '/admin/oauth2_provider/', 'has_module_perms': True, 'models': [{'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x04E320B0>, 'object_name': 'AccessToken', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/oauth2_provider/accesstoken/', 'add_url': '/admin/oauth2_provider/accesstoken/add/'}, {'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x04E328D0>, 'object_name': 'Application', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/oauth2_provider/application/', 'add_url': '/admin/oauth2_provider/application/add/'}, {'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x04E328B0>, 'object_name': 'Grant', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/oauth2_provider/grant/', 'add_url': '/admin/oauth2_provider/grant/add/'}, {'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x04E32B90>, 'object_name': 'RefreshToken', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/oauth2_provider/refreshtoken/', 'add_url': '/admin/oauth2_provider/refreshtoken/add/'}]}, {'name': 'Repositorio', 'app_label': 'repositorio', 'app_url': '/admin/repositorio/', 'has_module_perms': True, 'models': [{'name': 'Alquileres', 'object_name': 'Alquiler', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/repositorio/alquiler/', 'add_url': '/admin/repositorio/alquiler/add/'}, {'name': 'CargoPersonales', 'object_name': 'CargoPersonal', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/repositorio/cargopersonal/', 'add_url': '/admin/repositorio/cargopersonal/add/'}, {'name': 'Clientes', 'object_name': 'Cliente', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/repositorio/cliente/', 'add_url': '/admin/repositorio/cliente/add/'}, {'name': 'DetalleTarifarios', 'object_name': 'DetalleTarifario', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/repositorio/detalletarifario/', 'add_url': '/admin/repositorio/detalletarifario/add/'}, {'name': 'DetalleTiempoAlquileres', 'object_name': 'DetalleTiempoAlquiler', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/repositorio/detalletiempoalquiler/', 'add_url': '/admin/repositorio/detalletiempoalquiler/add/'}, {'name': 'DetalleUnidades', 'object_name': 'DetalleUnidad', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/repositorio/detalleunidad/', 'add_url': '/admin/repositorio/detalleunidad/add/'}, {'name': 'Personales', 'object_name': 'Personal', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/repositorio/personal/', 'add_url': '/admin/repositorio/personal/add/'}, {'name': 'Personas', 'object_name': 'Persona', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/repositorio/persona/', 'add_url': '/admin/repositorio/persona/add/'}, {'name': 'Proveedores', 'object_name': 'Proveedor', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/repositorio/proveedor/', 'add_url': '/admin/repositorio/proveedor/add/'}, {'name': 'RecepcionUnidades', 'object_name': 'RecepcionUnidad', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/repositorio/recepcionunidad/', 'add_url': '/admin/repositorio/recepcionunidad/add/'}, {'name': 'Rutas', 'object_name': 'Ruta', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/repositorio/ruta/', 'add_url': '/admin/repositorio/ruta/add/'}, {'name': 'Soats', 'object_name': 'Soat', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/repositorio/soat/', 'add_url': '/admin/repositorio/soat/add/'}, {'name': 'Tarifarios', 'object_name': 'Tarifario', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/repositorio/tarifario/', 'add_url': '/admin/repositorio/tarifario/add/'}, {'name': 'TiempoAlquileres', 'object_name': 'TiempoAlquiler', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/repositorio/tiempoalquiler/', 'add_url': '/admin/repositorio/tiempoalquiler/add/'}, {'name': 'Unidades', 'object_name': 'Unidad', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/repositorio/unidad/', 'add_url': '/admin/repositorio/unidad/add/'}, {'name': 'Usuarios', 'object_name': 'Usuario', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/repositorio/usuario/', 'add_url': '/admin/repositorio/usuario/add/'}]}, {'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x03CC7DB0>, 'app_label': 'contenttypes', 'app_url': '/admin/contenttypes/', 'has_module_perms': True, 'models': [{'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x04E32AB0>, 'object_name': 'ContentType', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/contenttypes/contenttype/', 'add_url': '/admin/contenttypes/contenttype/add/'}]}], 'title': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x03CBA9B0>, 'app_list': [{'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x03CC7F10>, 'app_label': 'auth', 'app_url': '/admin/auth/', 'has_module_perms': True, 'models': [{'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x047F9C50>, 'object_name': 'Group', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/auth/group/', 'add_url': '/admin/auth/group/add/'}, {'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x05300FB0>, 'object_name': 'Permission', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/auth/permission/', 'add_url': '/admin/auth/permission/add/'}]}, {'name': 'Auths', 'app_label': 'auths', 'app_url': '/admin/auths/', 'has_module_perms': True, 'models': [{'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x05300DB0>, 'object_name': 'HierarchyType', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/auths/hierarchytype/', 'add_url': '/admin/auths/hierarchytype/add/'}, {'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x05300CB0>, 'object_name': 'Hierarchy', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/auths/hierarchy/', 'add_url': '/admin/auths/hierarchy/add/'}, {'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x05300DD0>, 'object_name': 'Menu', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/auths/menu/', 'add_url': '/admin/auths/menu/add/'}, {'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x05300E10>, 'object_name': 'Person', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/auths/person/', 'add_url': '/admin/auths/person/add/'}, {'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x05300DF0>, 'object_name': 'UserHierarchyGroup', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/auths/userhierarchygroup/', 'add_url': '/admin/auths/userhierarchygroup/add/'}, {'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x05300E50>, 'object_name': 'UserHierarchyPermission', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/auths/userhierarchypermission/', 'add_url': '/admin/auths/userhierarchypermission/add/'}, {'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x05300FD0>, 'object_name': 'User', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/auths/user/', 'add_url': '/admin/auths/user/add/'}]}, {'name': 'Django OAuth Toolkit', 'app_label': 'oauth2_provider', 'app_url': '/admin/oauth2_provider/', 'has_module_perms': True, 'models': [{'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x05367710>, 'object_name': 'AccessToken', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/oauth2_provider/accesstoken/', 'add_url': '/admin/oauth2_provider/accesstoken/add/'}, {'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x047F9950>, 'object_name': 'Application', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/oauth2_provider/application/', 'add_url': '/admin/oauth2_provider/application/add/'}, {'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x053676D0>, 'object_name': 'Grant', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/oauth2_provider/grant/', 'add_url': '/admin/oauth2_provider/grant/add/'}, {'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x05300FF0>, 'object_name': 'RefreshToken', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/oauth2_provider/refreshtoken/', 'add_url': '/admin/oauth2_provider/refreshtoken/add/'}]}, {'name': 'Repositorio', 'app_label': 'repositorio', 'app_url': '/admin/repositorio/', 'has_module_perms': True, 'models': [{'name': 'Alquileres', 'object_name': 'Alquiler', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/repositorio/alquiler/', 'add_url': '/admin/repositorio/alquiler/add/'}, {'name': 'CargoPersonales', 'object_name': 'CargoPersonal', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/repositorio/cargopersonal/', 'add_url': '/admin/repositorio/cargopersonal/add/'}, {'name': 'Clientes', 'object_name': 'Cliente', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/repositorio/cliente/', 'add_url': '/admin/repositorio/cliente/add/'}, {'name': 'DetalleTarifarios', 'object_name': 'DetalleTarifario', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/repositorio/detalletarifario/', 'add_url': '/admin/repositorio/detalletarifario/add/'}, {'name': 'DetalleTiempoAlquileres', 'object_name': 'DetalleTiempoAlquiler', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/repositorio/detalletiempoalquiler/', 'add_url': '/admin/repositorio/detalletiempoalquiler/add/'}, {'name': 'DetalleUnidades', 'object_name': 'DetalleUnidad', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/repositorio/detalleunidad/', 'add_url': '/admin/repositorio/detalleunidad/add/'}, {'name': 'Personales', 'object_name': 'Personal', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/repositorio/personal/', 'add_url': '/admin/repositorio/personal/add/'}, {'name': 'Personas', 'object_name': 'Persona', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/repositorio/persona/', 'add_url': '/admin/repositorio/persona/add/'}, {'name': 'Proveedores', 'object_name': 'Proveedor', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/repositorio/proveedor/', 'add_url': '/admin/repositorio/proveedor/add/'}, {'name': 'RecepcionUnidades', 'object_name': 'RecepcionUnidad', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/repositorio/recepcionunidad/', 'add_url': '/admin/repositorio/recepcionunidad/add/'}, {'name': 'Rutas', 'object_name': 'Ruta', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/repositorio/ruta/', 'add_url': '/admin/repositorio/ruta/add/'}, {'name': 'Soats', 'object_name': 'Soat', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/repositorio/soat/', 'add_url': '/admin/repositorio/soat/add/'}, {'name': 'Tarifarios', 'object_name': 'Tarifario', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/repositorio/tarifario/', 'add_url': '/admin/repositorio/tarifario/add/'}, {'name': 'TiempoAlquileres', 'object_name': 'TiempoAlquiler', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/repositorio/tiempoalquiler/', 'add_url': '/admin/repositorio/tiempoalquiler/add/'}, {'name': 'Unidades', 'object_name': 'Unidad', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/repositorio/unidad/', 'add_url': '/admin/repositorio/unidad/add/'}, {'name': 'Usuarios', 'object_name': 'Usuario', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/repositorio/usuario/', 'add_url': '/admin/repositorio/usuario/add/'}]}, {'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x03CC7DB0>, 'app_label': 'contenttypes', 'app_url': '/admin/contenttypes/', 'has_module_perms': True, 'models': [{'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x05300F90>, 'object_name': 'ContentType', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/contenttypes/contenttype/', 'add_url': '/admin/contenttypes/contenttype/add/'}]}], 'LANGUAGE_CODE': 'es', 'LANGUAGE_BIDI': False}]"
[2017-11-08 15:39:16] DEBUG [django.template:929] Exception while resolving variable 'is_popup' in template 'admin/index.html'.
Traceback (most recent call last):
  File "E:\Proyecto2017\translipsur\ve_translipsur\lib\site-packages\django\template\base.py", line 885, in _resolve_lookup
    current = current[bit]
  File "E:\Proyecto2017\translipsur\ve_translipsur\lib\site-packages\django\template\context.py", line 75, in __getitem__
    raise KeyError(key)
KeyError: 'is_popup'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Proyecto2017\translipsur\ve_translipsur\lib\site-packages\django\template\base.py", line 891, in _resolve_lookup
    if isinstance(current, BaseContext) and getattr(type(current), bit):
AttributeError: type object 'RequestContext' has no attribute 'is_popup'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Proyecto2017\translipsur\ve_translipsur\lib\site-packages\django\template\base.py", line 900, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'is_popup'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Proyecto2017\translipsur\ve_translipsur\lib\site-packages\django\template\base.py", line 907, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [is_popup] in "[{'True': True, 'False': False, 'None': None}, {'csrf_token': <SimpleLazyObject: <function csrf.<locals>._get_val at 0x05375150>>, 'request': <WSGIRequest: GET '/admin/'>, 'user': <SimpleLazyObject: <User: nogami>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x053F7250>, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x047F9E50>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'SUCCESS': 25, 'WARNING': 30, 'ERROR': 40}}, {}, {'site_title': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x03CB0EF0>, 'site_header': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x03CB0F30>, 'site_url': '/', 'has_permission': True, 'available_apps': [{'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x03CC7F10>, 'app_label': 'auth', 'app_url': '/admin/auth/', 'has_module_perms': True, 'models': [{'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x04E32710>, 'object_name': 'Group', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/auth/group/', 'add_url': '/admin/auth/group/add/'}, {'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x04E32CB0>, 'object_name': 'Permission', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/auth/permission/', 'add_url': '/admin/auth/permission/add/'}]}, {'name': 'Auths', 'app_label': 'auths', 'app_url': '/admin/auths/', 'has_module_perms': True, 'models': [{'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x04E32C50>, 'object_name': 'HierarchyType', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/auths/hierarchytype/', 'add_url': '/admin/auths/hierarchytype/add/'}, {'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x04E32B10>, 'object_name': 'Hierarchy', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/auths/hierarchy/', 'add_url': '/admin/auths/hierarchy/add/'}, {'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x04E32E50>, 'object_name': 'Menu', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/auths/menu/', 'add_url': '/admin/auths/menu/add/'}, {'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x04E32EF0>, 'object_name': 'Person', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/auths/person/', 'add_url': '/admin/auths/person/add/'}, {'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x04E32C70>, 'object_name': 'UserHierarchyGroup', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/auths/userhierarchygroup/', 'add_url': '/admin/auths/userhierarchygroup/add/'}, {'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x04E32E70>, 'object_name': 'UserHierarchyPermission', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/auths/userhierarchypermission/', 'add_url': '/admin/auths/userhierarchypermission/add/'}, {'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x0531FDB0>, 'object_name': 'User', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/auths/user/', 'add_url': '/admin/auths/user/add/'}]}, {'name': 'Django OAuth Toolkit', 'app_label': 'oauth2_provider', 'app_url': '/admin/oauth2_provider/', 'has_module_perms': True, 'models': [{'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x04E320B0>, 'object_name': 'AccessToken', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/oauth2_provider/accesstoken/', 'add_url': '/admin/oauth2_provider/accesstoken/add/'}, {'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x04E328D0>, 'object_name': 'Application', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/oauth2_provider/application/', 'add_url': '/admin/oauth2_provider/application/add/'}, {'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x04E328B0>, 'object_name': 'Grant', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/oauth2_provider/grant/', 'add_url': '/admin/oauth2_provider/grant/add/'}, {'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x04E32B90>, 'object_name': 'RefreshToken', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/oauth2_provider/refreshtoken/', 'add_url': '/admin/oauth2_provider/refreshtoken/add/'}]}, {'name': 'Repositorio', 'app_label': 'repositorio', 'app_url': '/admin/repositorio/', 'has_module_perms': True, 'models': [{'name': 'Alquileres', 'object_name': 'Alquiler', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/repositorio/alquiler/', 'add_url': '/admin/repositorio/alquiler/add/'}, {'name': 'CargoPersonales', 'object_name': 'CargoPersonal', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/repositorio/cargopersonal/', 'add_url': '/admin/repositorio/cargopersonal/add/'}, {'name': 'Clientes', 'object_name': 'Cliente', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/repositorio/cliente/', 'add_url': '/admin/repositorio/cliente/add/'}, {'name': 'DetalleTarifarios', 'object_name': 'DetalleTarifario', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/repositorio/detalletarifario/', 'add_url': '/admin/repositorio/detalletarifario/add/'}, {'name': 'DetalleTiempoAlquileres', 'object_name': 'DetalleTiempoAlquiler', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/repositorio/detalletiempoalquiler/', 'add_url': '/admin/repositorio/detalletiempoalquiler/add/'}, {'name': 'DetalleUnidades', 'object_name': 'DetalleUnidad', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/repositorio/detalleunidad/', 'add_url': '/admin/repositorio/detalleunidad/add/'}, {'name': 'Personales', 'object_name': 'Personal', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/repositorio/personal/', 'add_url': '/admin/repositorio/personal/add/'}, {'name': 'Personas', 'object_name': 'Persona', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/repositorio/persona/', 'add_url': '/admin/repositorio/persona/add/'}, {'name': 'Proveedores', 'object_name': 'Proveedor', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/repositorio/proveedor/', 'add_url': '/admin/repositorio/proveedor/add/'}, {'name': 'RecepcionUnidades', 'object_name': 'RecepcionUnidad', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/repositorio/recepcionunidad/', 'add_url': '/admin/repositorio/recepcionunidad/add/'}, {'name': 'Rutas', 'object_name': 'Ruta', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/repositorio/ruta/', 'add_url': '/admin/repositorio/ruta/add/'}, {'name': 'Soats', 'object_name': 'Soat', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/repositorio/soat/', 'add_url': '/admin/repositorio/soat/add/'}, {'name': 'Tarifarios', 'object_name': 'Tarifario', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/repositorio/tarifario/', 'add_url': '/admin/repositorio/tarifario/add/'}, {'name': 'TiempoAlquileres', 'object_name': 'TiempoAlquiler', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/repositorio/tiempoalquiler/', 'add_url': '/admin/repositorio/tiempoalquiler/add/'}, {'name': 'Unidades', 'object_name': 'Unidad', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/repositorio/unidad/', 'add_url': '/admin/repositorio/unidad/add/'}, {'name': 'Usuarios', 'object_name': 'Usuario', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/repositorio/usuario/', 'add_url': '/admin/repositorio/usuario/add/'}]}, {'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x03CC7DB0>, 'app_label': 'contenttypes', 'app_url': '/admin/contenttypes/', 'has_module_perms': True, 'models': [{'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x04E32AB0>, 'object_name': 'ContentType', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/contenttypes/contenttype/', 'add_url': '/admin/contenttypes/contenttype/add/'}]}], 'title': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x03CBA9B0>, 'app_list': [{'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x03CC7F10>, 'app_label': 'auth', 'app_url': '/admin/auth/', 'has_module_perms': True, 'models': [{'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x047F9C50>, 'object_name': 'Group', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/auth/group/', 'add_url': '/admin/auth/group/add/'}, {'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x05300FB0>, 'object_name': 'Permission', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/auth/permission/', 'add_url': '/admin/auth/permission/add/'}]}, {'name': 'Auths', 'app_label': 'auths', 'app_url': '/admin/auths/', 'has_module_perms': True, 'models': [{'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x05300DB0>, 'object_name': 'HierarchyType', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/auths/hierarchytype/', 'add_url': '/admin/auths/hierarchytype/add/'}, {'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x05300CB0>, 'object_name': 'Hierarchy', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/auths/hierarchy/', 'add_url': '/admin/auths/hierarchy/add/'}, {'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x05300DD0>, 'object_name': 'Menu', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/auths/menu/', 'add_url': '/admin/auths/menu/add/'}, {'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x05300E10>, 'object_name': 'Person', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/auths/person/', 'add_url': '/admin/auths/person/add/'}, {'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x05300DF0>, 'object_name': 'UserHierarchyGroup', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/auths/userhierarchygroup/', 'add_url': '/admin/auths/userhierarchygroup/add/'}, {'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x05300E50>, 'object_name': 'UserHierarchyPermission', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/auths/userhierarchypermission/', 'add_url': '/admin/auths/userhierarchypermission/add/'}, {'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x05300FD0>, 'object_name': 'User', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/auths/user/', 'add_url': '/admin/auths/user/add/'}]}, {'name': 'Django OAuth Toolkit', 'app_label': 'oauth2_provider', 'app_url': '/admin/oauth2_provider/', 'has_module_perms': True, 'models': [{'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x05367710>, 'object_name': 'AccessToken', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/oauth2_provider/accesstoken/', 'add_url': '/admin/oauth2_provider/accesstoken/add/'}, {'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x047F9950>, 'object_name': 'Application', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/oauth2_provider/application/', 'add_url': '/admin/oauth2_provider/application/add/'}, {'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x053676D0>, 'object_name': 'Grant', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/oauth2_provider/grant/', 'add_url': '/admin/oauth2_provider/grant/add/'}, {'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x05300FF0>, 'object_name': 'RefreshToken', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/oauth2_provider/refreshtoken/', 'add_url': '/admin/oauth2_provider/refreshtoken/add/'}]}, {'name': 'Repositorio', 'app_label': 'repositorio', 'app_url': '/admin/repositorio/', 'has_module_perms': True, 'models': [{'name': 'Alquileres', 'object_name': 'Alquiler', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/repositorio/alquiler/', 'add_url': '/admin/repositorio/alquiler/add/'}, {'name': 'CargoPersonales', 'object_name': 'CargoPersonal', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/repositorio/cargopersonal/', 'add_url': '/admin/repositorio/cargopersonal/add/'}, {'name': 'Clientes', 'object_name': 'Cliente', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/repositorio/cliente/', 'add_url': '/admin/repositorio/cliente/add/'}, {'name': 'DetalleTarifarios', 'object_name': 'DetalleTarifario', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/repositorio/detalletarifario/', 'add_url': '/admin/repositorio/detalletarifario/add/'}, {'name': 'DetalleTiempoAlquileres', 'object_name': 'DetalleTiempoAlquiler', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/repositorio/detalletiempoalquiler/', 'add_url': '/admin/repositorio/detalletiempoalquiler/add/'}, {'name': 'DetalleUnidades', 'object_name': 'DetalleUnidad', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/repositorio/detalleunidad/', 'add_url': '/admin/repositorio/detalleunidad/add/'}, {'name': 'Personales', 'object_name': 'Personal', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/repositorio/personal/', 'add_url': '/admin/repositorio/personal/add/'}, {'name': 'Personas', 'object_name': 'Persona', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/repositorio/persona/', 'add_url': '/admin/repositorio/persona/add/'}, {'name': 'Proveedores', 'object_name': 'Proveedor', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/repositorio/proveedor/', 'add_url': '/admin/repositorio/proveedor/add/'}, {'name': 'RecepcionUnidades', 'object_name': 'RecepcionUnidad', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/repositorio/recepcionunidad/', 'add_url': '/admin/repositorio/recepcionunidad/add/'}, {'name': 'Rutas', 'object_name': 'Ruta', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/repositorio/ruta/', 'add_url': '/admin/repositorio/ruta/add/'}, {'name': 'Soats', 'object_name': 'Soat', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/repositorio/soat/', 'add_url': '/admin/repositorio/soat/add/'}, {'name': 'Tarifarios', 'object_name': 'Tarifario', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/repositorio/tarifario/', 'add_url': '/admin/repositorio/tarifario/add/'}, {'name': 'TiempoAlquileres', 'object_name': 'TiempoAlquiler', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/repositorio/tiempoalquiler/', 'add_url': '/admin/repositorio/tiempoalquiler/add/'}, {'name': 'Unidades', 'object_name': 'Unidad', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/repositorio/unidad/', 'add_url': '/admin/repositorio/unidad/add/'}, {'name': 'Usuarios', 'object_name': 'Usuario', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/repositorio/usuario/', 'add_url': '/admin/repositorio/usuario/add/'}]}, {'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x03CC7DB0>, 'app_label': 'contenttypes', 'app_url': '/admin/contenttypes/', 'has_module_perms': True, 'models': [{'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x05300F90>, 'object_name': 'ContentType', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/contenttypes/contenttype/', 'add_url': '/admin/contenttypes/contenttype/add/'}]}], 'LANGUAGE_CODE': 'es', 'LANGUAGE_BIDI': False}]"
[2017-11-08 15:39:16] DEBUG [django.db.backends:90] (0.001) SELECT "django_admin_log"."id", "django_admin_log"."action_time", "django_admin_log"."user_id", "django_admin_log"."content_type_id", "django_admin_log"."object_id", "django_admin_log"."object_repr", "django_admin_log"."action_flag", "django_admin_log"."change_message", "auths_user"."password", "auths_user"."last_login", "auths_user"."is_superuser", "auths_user"."username", "auths_user"."first_name", "auths_user"."last_name", "auths_user"."email", "auths_user"."is_staff", "auths_user"."is_active", "auths_user"."date_joined", "auths_user"."id", "auths_user"."last_hierarchy_id", "auths_user"."last_module_id", "auths_user"."person_id", "auths_user"."updated_at", "auths_user"."registered_by", "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_admin_log" INNER JOIN "auths_user" ON ("django_admin_log"."user_id" = "auths_user"."id") LEFT OUTER JOIN "django_content_type" ON ("django_admin_log"."content_type_id" = "django_content_type"."id") WHERE "django_admin_log"."user_id" = 'aa19e6b5cb564a9c8bdebe3d66e6760e' ORDER BY "django_admin_log"."action_time" DESC LIMIT 10; args=('aa19e6b5cb564a9c8bdebe3d66e6760e',)
[2017-11-08 15:39:16] INFO [django.server:131] "GET /admin/ HTTP/1.1" 200 19871
[2017-11-08 15:39:17] INFO [django.server:131] "GET /static/admin/css/base.css HTTP/1.1" 304 0
[2017-11-08 15:39:17] INFO [django.server:131] "GET /static/admin/css/dashboard.css HTTP/1.1" 304 0
[2017-11-08 15:39:17] INFO [django.server:131] "GET /static/admin/css/fonts.css HTTP/1.1" 304 0
[2017-11-08 15:39:17] INFO [django.server:131] "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 304 0
[2017-11-08 15:39:17] INFO [django.server:131] "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 304 0
[2017-11-08 15:39:17] INFO [django.server:131] "GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 304 0
[2017-11-08 15:39:17] INFO [django.server:131] "GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 304 0
[2017-11-08 15:39:17] INFO [django.server:131] "GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 304 0
[2017-11-08 15:39:21] DEBUG [django.db.backends:90] (0.002) SELECT "django_session"."session_key", "django_session"."session_data", "django_session"."expire_date" FROM "django_session" WHERE ("django_session"."session_key" = 'l241eicyrsisp20pz2p7xafbun3a3s1h' AND "django_session"."expire_date" > '2017-11-08 20:39:21.951787'); args=('l241eicyrsisp20pz2p7xafbun3a3s1h', '2017-11-08 20:39:21.951787')
[2017-11-08 15:39:21] DEBUG [django.db.backends:90] (0.000) SELECT "auths_user"."password", "auths_user"."last_login", "auths_user"."is_superuser", "auths_user"."username", "auths_user"."first_name", "auths_user"."last_name", "auths_user"."email", "auths_user"."is_staff", "auths_user"."is_active", "auths_user"."date_joined", "auths_user"."id", "auths_user"."last_hierarchy_id", "auths_user"."last_module_id", "auths_user"."person_id", "auths_user"."updated_at", "auths_user"."registered_by" FROM "auths_user" WHERE "auths_user"."id" = 'aa19e6b5cb564a9c8bdebe3d66e6760e'; args=('aa19e6b5cb564a9c8bdebe3d66e6760e',)
[2017-11-08 15:39:21] DEBUG [django.db.backends:90] (0.000) SELECT COUNT(*) AS "__count" FROM "repositorio_persona"; args=()
[2017-11-08 15:39:21] DEBUG [django.db.backends:90] (0.000) SELECT COUNT(*) AS "__count" FROM "repositorio_persona"; args=()
[2017-11-08 15:39:21] DEBUG [django.db.backends:90] (0.001) SELECT "repositorio_persona"."id", "repositorio_persona"."nombre", "repositorio_persona"."ape_paterno", "repositorio_persona"."ape_materno", "repositorio_persona"."dni", "repositorio_persona"."ruc", "repositorio_persona"."celular", "repositorio_persona"."tipo_persona", "repositorio_persona"."direccion", "repositorio_persona"."departamento", "repositorio_persona"."provincia", "repositorio_persona"."distrito" FROM "repositorio_persona" ORDER BY "repositorio_persona"."id" DESC LIMIT 3; args=()
[2017-11-08 15:39:22] DEBUG [django.template:929] Exception while resolving variable 'errors' in template 'admin/change_list.html'.
Traceback (most recent call last):
  File "E:\Proyecto2017\translipsur\ve_translipsur\lib\site-packages\django\template\base.py", line 885, in _resolve_lookup
    current = current[bit]
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Proyecto2017\translipsur\ve_translipsur\lib\site-packages\django\template\base.py", line 893, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'NoneType' object has no attribute 'errors'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Proyecto2017\translipsur\ve_translipsur\lib\site-packages\django\template\base.py", line 900, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'errors'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Proyecto2017\translipsur\ve_translipsur\lib\site-packages\django\template\base.py", line 907, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [errors] in 'None'
[2017-11-08 15:39:22] DEBUG [django.template:929] Exception while resolving variable 'show' in template 'admin/change_list.html'.
Traceback (most recent call last):
  File "E:\Proyecto2017\translipsur\ve_translipsur\lib\site-packages\django\template\base.py", line 885, in _resolve_lookup
    current = current[bit]
  File "E:\Proyecto2017\translipsur\ve_translipsur\lib\site-packages\django\template\context.py", line 75, in __getitem__
    raise KeyError(key)
KeyError: 'show'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Proyecto2017\translipsur\ve_translipsur\lib\site-packages\django\template\base.py", line 891, in _resolve_lookup
    if isinstance(current, BaseContext) and getattr(type(current), bit):
AttributeError: type object 'RequestContext' has no attribute 'show'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Proyecto2017\translipsur\ve_translipsur\lib\site-packages\django\template\base.py", line 900, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'show'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Proyecto2017\translipsur\ve_translipsur\lib\site-packages\django\template\base.py", line 907, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [show] in "[{'True': True, 'False': False, 'None': None, 'csrf_token': <SimpleLazyObject: <function csrf.<locals>._get_val at 0x0542C108>>}]"
[2017-11-08 15:39:22] DEBUG [django.template:929] Exception while resolving variable 'is_multipart' in template 'admin/change_list.html'.
Traceback (most recent call last):
  File "E:\Proyecto2017\translipsur\ve_translipsur\lib\site-packages\django\template\base.py", line 885, in _resolve_lookup
    current = current[bit]
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Proyecto2017\translipsur\ve_translipsur\lib\site-packages\django\template\base.py", line 893, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'NoneType' object has no attribute 'is_multipart'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Proyecto2017\translipsur\ve_translipsur\lib\site-packages\django\template\base.py", line 900, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'is_multipart'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Proyecto2017\translipsur\ve_translipsur\lib\site-packages\django\template\base.py", line 907, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [is_multipart] in 'None'
[2017-11-08 15:39:22] DEBUG [django.template:929] Exception while resolving variable 'non_field_errors' in template 'admin/change_list.html'.
Traceback (most recent call last):
  File "E:\Proyecto2017\translipsur\ve_translipsur\lib\site-packages\django\template\base.py", line 885, in _resolve_lookup
    current = current[bit]
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Proyecto2017\translipsur\ve_translipsur\lib\site-packages\django\template\base.py", line 893, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'NoneType' object has no attribute 'non_field_errors'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Proyecto2017\translipsur\ve_translipsur\lib\site-packages\django\template\base.py", line 900, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'non_field_errors'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Proyecto2017\translipsur\ve_translipsur\lib\site-packages\django\template\base.py", line 907, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [non_field_errors] in 'None'
[2017-11-08 15:39:22] DEBUG [django.template:929] Exception while resolving variable 'non_field_errors' in template 'admin/change_list.html'.
Traceback (most recent call last):
  File "E:\Proyecto2017\translipsur\ve_translipsur\lib\site-packages\django\template\base.py", line 885, in _resolve_lookup
    current = current[bit]
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Proyecto2017\translipsur\ve_translipsur\lib\site-packages\django\template\base.py", line 893, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'NoneType' object has no attribute 'non_field_errors'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Proyecto2017\translipsur\ve_translipsur\lib\site-packages\django\template\base.py", line 900, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'non_field_errors'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Proyecto2017\translipsur\ve_translipsur\lib\site-packages\django\template\base.py", line 907, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [non_field_errors] in 'None'
[2017-11-08 15:39:22] DEBUG [django.template:929] Exception while resolving variable 'non_field_errors' in template 'admin/change_list.html'.
Traceback (most recent call last):
  File "E:\Proyecto2017\translipsur\ve_translipsur\lib\site-packages\django\template\base.py", line 885, in _resolve_lookup
    current = current[bit]
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Proyecto2017\translipsur\ve_translipsur\lib\site-packages\django\template\base.py", line 893, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'NoneType' object has no attribute 'non_field_errors'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Proyecto2017\translipsur\ve_translipsur\lib\site-packages\django\template\base.py", line 900, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'non_field_errors'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Proyecto2017\translipsur\ve_translipsur\lib\site-packages\django\template\base.py", line 907, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [non_field_errors] in 'None'
[2017-11-08 15:39:22] INFO [django.server:131] "GET /admin/repositorio/persona/ HTTP/1.1" 200 8616
[2017-11-08 15:39:22] INFO [django.server:131] "GET /static/admin/css/changelists.css HTTP/1.1" 304 0
[2017-11-08 15:39:22] DEBUG [django.db.backends:90] (0.004) SELECT "django_session"."session_key", "django_session"."session_data", "django_session"."expire_date" FROM "django_session" WHERE ("django_session"."session_key" = 'l241eicyrsisp20pz2p7xafbun3a3s1h' AND "django_session"."expire_date" > '2017-11-08 20:39:22.445719'); args=('l241eicyrsisp20pz2p7xafbun3a3s1h', '2017-11-08 20:39:22.445719')
[2017-11-08 15:39:22] DEBUG [django.db.backends:90] (0.001) SELECT "auths_user"."password", "auths_user"."last_login", "auths_user"."is_superuser", "auths_user"."username", "auths_user"."first_name", "auths_user"."last_name", "auths_user"."email", "auths_user"."is_staff", "auths_user"."is_active", "auths_user"."date_joined", "auths_user"."id", "auths_user"."last_hierarchy_id", "auths_user"."last_module_id", "auths_user"."person_id", "auths_user"."updated_at", "auths_user"."registered_by" FROM "auths_user" WHERE "auths_user"."id" = 'aa19e6b5cb564a9c8bdebe3d66e6760e'; args=('aa19e6b5cb564a9c8bdebe3d66e6760e',)
[2017-11-08 15:39:22] INFO [django.server:131] "GET /admin/jsi18n/ HTTP/1.1" 200 7035
[2017-11-08 15:39:22] INFO [django.server:131] "GET /static/admin/js/core.js HTTP/1.1" 304 0
[2017-11-08 15:39:22] INFO [django.server:131] "GET /static/admin/js/jquery.init.js HTTP/1.1" 304 0
[2017-11-08 15:39:22] INFO [django.server:131] "GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 304 0
[2017-11-08 15:39:22] INFO [django.server:131] "GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 304 0
[2017-11-08 15:39:22] INFO [django.server:131] "GET /static/admin/js/actions.js HTTP/1.1" 304 0
[2017-11-08 15:39:22] INFO [django.server:131] "GET /static/admin/js/urlify.js HTTP/1.1" 304 0
[2017-11-08 15:39:22] INFO [django.server:131] "GET /static/admin/js/prepopulate.js HTTP/1.1" 304 0
[2017-11-08 15:39:22] INFO [django.server:131] "GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 304 0
[2017-11-08 15:39:23] INFO [django.server:131] "GET /static/admin/img/search.svg HTTP/1.1" 304 0
[2017-11-08 15:39:23] INFO [django.server:131] "GET /static/admin/img/tooltag-add.svg HTTP/1.1" 304 0
[2017-11-08 17:21:03] DEBUG [django.db.backends:90] (0.004) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
[2017-11-08 17:21:03] DEBUG [django.db.backends:90] (0.001) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
[2017-11-08 17:21:45] WARNING [django.server:131] "GET /api/auths/localuserinfo/ HTTP/1.1" 401 65
[2017-11-08 17:21:45] WARNING [django.server:131] "GET /api/auths/usermenu/ HTTP/1.1" 401 65
[2017-11-08 17:21:53] DEBUG [django.db.backends:90] (0.003) SELECT "repositorio_usuario"."id", "repositorio_usuario"."user", "repositorio_usuario"."password", "repositorio_usuario"."fecha_creada", "repositorio_usuario"."fecha_actualizada", "repositorio_usuario"."persona_id", "repositorio_usuario"."estado" FROM "repositorio_usuario" WHERE ("repositorio_usuario"."id" LIKE '%%' ESCAPE '\' OR "repositorio_usuario"."user" LIKE '%%' ESCAPE '\'); args=('%%', '%%')
[2017-11-08 17:21:53] DEBUG [django.db.backends:90] (0.000) SELECT "repositorio_persona"."id", "repositorio_persona"."nombre", "repositorio_persona"."ape_paterno", "repositorio_persona"."ape_materno", "repositorio_persona"."dni", "repositorio_persona"."ruc", "repositorio_persona"."celular", "repositorio_persona"."tipo_persona", "repositorio_persona"."direccion", "repositorio_persona"."departamento", "repositorio_persona"."provincia", "repositorio_persona"."distrito" FROM "repositorio_persona" WHERE "repositorio_persona"."id" = 'eb0d78a6fd5c49da81399fc41cb844ff'; args=('eb0d78a6fd5c49da81399fc41cb844ff',)
[2017-11-08 17:21:53] DEBUG [django.db.backends:90] (0.001) SELECT "repositorio_persona"."id", "repositorio_persona"."nombre", "repositorio_persona"."ape_paterno", "repositorio_persona"."ape_materno", "repositorio_persona"."dni", "repositorio_persona"."ruc", "repositorio_persona"."celular", "repositorio_persona"."tipo_persona", "repositorio_persona"."direccion", "repositorio_persona"."departamento", "repositorio_persona"."provincia", "repositorio_persona"."distrito" FROM "repositorio_persona" WHERE "repositorio_persona"."id" = '10a870a9f7e045fbbfd6cc31180e2078'; args=('10a870a9f7e045fbbfd6cc31180e2078',)
[2017-11-08 17:21:53] DEBUG [django.db.backends:90] (0.000) SELECT "repositorio_persona"."id", "repositorio_persona"."nombre", "repositorio_persona"."ape_paterno", "repositorio_persona"."ape_materno", "repositorio_persona"."dni", "repositorio_persona"."ruc", "repositorio_persona"."celular", "repositorio_persona"."tipo_persona", "repositorio_persona"."direccion", "repositorio_persona"."departamento", "repositorio_persona"."provincia", "repositorio_persona"."distrito" FROM "repositorio_persona" WHERE "repositorio_persona"."id" = 'e1b96617c94342d595b1952204fbeba8'; args=('e1b96617c94342d595b1952204fbeba8',)
[2017-11-08 17:21:53] DEBUG [django.db.backends:90] (0.000) SELECT "repositorio_persona"."id", "repositorio_persona"."nombre", "repositorio_persona"."ape_paterno", "repositorio_persona"."ape_materno", "repositorio_persona"."dni", "repositorio_persona"."ruc", "repositorio_persona"."celular", "repositorio_persona"."tipo_persona", "repositorio_persona"."direccion", "repositorio_persona"."departamento", "repositorio_persona"."provincia", "repositorio_persona"."distrito" FROM "repositorio_persona" WHERE "repositorio_persona"."id" = '71623f0d91804af1b4e6634c533812da'; args=('71623f0d91804af1b4e6634c533812da',)
[2017-11-08 17:21:53] INFO [django.server:131] "GET /api/repositorio/usuarios/ HTTP/1.1" 200 1056
[2017-11-08 17:45:05] DEBUG [django.db.backends:90] (0.003) SELECT "repositorio_detalleunidad"."id", "repositorio_detalleunidad"."descripcion", "repositorio_detalleunidad"."costo", "repositorio_detalleunidad"."fecha_creada", "repositorio_detalleunidad"."fecha_actualizada", "repositorio_detalleunidad"."proveedor_id", "repositorio_detalleunidad"."unidad_id" FROM "repositorio_detalleunidad" WHERE ("repositorio_detalleunidad"."id" LIKE '%%' ESCAPE '\' OR "repositorio_detalleunidad"."costo" LIKE '%%' ESCAPE '\' OR "repositorio_detalleunidad"."descripcion" LIKE '%%' ESCAPE '\'); args=('%%', '%%', '%%')
[2017-11-08 17:45:05] DEBUG [django.db.backends:90] (0.001) SELECT "repositorio_proveedor"."id", "repositorio_proveedor"."nombre", "repositorio_proveedor"."pagina_web", "repositorio_proveedor"."estado", "repositorio_proveedor"."persona_id" FROM "repositorio_proveedor" WHERE "repositorio_proveedor"."id" = '36dc5377212d4615aaf64aabc52b25aa'; args=('36dc5377212d4615aaf64aabc52b25aa',)
[2017-11-08 17:45:05] DEBUG [django.db.backends:90] (0.000) SELECT "repositorio_unidad"."id", "repositorio_unidad"."marca", "repositorio_unidad"."placa", "repositorio_unidad"."color", "repositorio_unidad"."tipo_combustible", "repositorio_unidad"."ruedas", "repositorio_unidad"."altura", "repositorio_unidad"."ancho", "repositorio_unidad"."tipo", "repositorio_unidad"."cilindros", "repositorio_unidad"."ejes", "repositorio_unidad"."nro_motor", "repositorio_unidad"."km_recorrido", "repositorio_unidad"."ano_modelo", "repositorio_unidad"."asientos", "repositorio_unidad"."carga_util", "repositorio_unidad"."longitud", "repositorio_unidad"."nro_serie", "repositorio_unidad"."pasajeros", "repositorio_unidad"."peso_bruto", "repositorio_unidad"."peso_seco" FROM "repositorio_unidad" WHERE "repositorio_unidad"."id" = 'ea9f71d358304da8a078d262b40f239d'; args=('ea9f71d358304da8a078d262b40f239d',)
[2017-11-08 17:45:05] DEBUG [django.db.backends:90] (0.001) SELECT "repositorio_proveedor"."id", "repositorio_proveedor"."nombre", "repositorio_proveedor"."pagina_web", "repositorio_proveedor"."estado", "repositorio_proveedor"."persona_id" FROM "repositorio_proveedor" WHERE "repositorio_proveedor"."id" = '8616f1dfa07b442f91f870e83be9f577'; args=('8616f1dfa07b442f91f870e83be9f577',)
[2017-11-08 17:45:05] DEBUG [django.db.backends:90] (0.001) SELECT "repositorio_unidad"."id", "repositorio_unidad"."marca", "repositorio_unidad"."placa", "repositorio_unidad"."color", "repositorio_unidad"."tipo_combustible", "repositorio_unidad"."ruedas", "repositorio_unidad"."altura", "repositorio_unidad"."ancho", "repositorio_unidad"."tipo", "repositorio_unidad"."cilindros", "repositorio_unidad"."ejes", "repositorio_unidad"."nro_motor", "repositorio_unidad"."km_recorrido", "repositorio_unidad"."ano_modelo", "repositorio_unidad"."asientos", "repositorio_unidad"."carga_util", "repositorio_unidad"."longitud", "repositorio_unidad"."nro_serie", "repositorio_unidad"."pasajeros", "repositorio_unidad"."peso_bruto", "repositorio_unidad"."peso_seco" FROM "repositorio_unidad" WHERE "repositorio_unidad"."id" = 'ea9f71d358304da8a078d262b40f239d'; args=('ea9f71d358304da8a078d262b40f239d',)
[2017-11-08 17:45:05] INFO [django.server:131] "GET /api/repositorio/detalleUnidades/ HTTP/1.1" 200 668
[2017-11-08 20:33:45] DEBUG [django.db.backends:90] (0.003) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
[2017-11-08 20:33:45] DEBUG [django.db.backends:90] (0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
[2017-11-08 20:36:32] DEBUG [django.db.backends:90] (0.003) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
[2017-11-08 20:36:32] DEBUG [django.db.backends:90] (0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
[2017-11-08 20:37:31] WARNING [django.server:131] "GET /api/auths/localuserinfo/ HTTP/1.1" 401 65
[2017-11-08 20:37:31] WARNING [django.server:131] "GET /api/auths/usermenu/ HTTP/1.1" 401 65
[2017-11-08 20:37:31] DEBUG [django.db.backends:90] (0.005) SELECT "repositorio_detalleunidad"."id", "repositorio_detalleunidad"."descripcion", "repositorio_detalleunidad"."costo", "repositorio_detalleunidad"."fecha_creada", "repositorio_detalleunidad"."fecha_actualizada", "repositorio_detalleunidad"."proveedor_id", "repositorio_detalleunidad"."unidad_id" FROM "repositorio_detalleunidad" WHERE ("repositorio_detalleunidad"."id" LIKE '%%' ESCAPE '\' OR "repositorio_detalleunidad"."costo" LIKE '%%' ESCAPE '\' OR "repositorio_detalleunidad"."descripcion" LIKE '%%' ESCAPE '\'); args=('%%', '%%', '%%')
[2017-11-08 20:37:31] DEBUG [django.db.backends:90] (0.001) SELECT "repositorio_proveedor"."id", "repositorio_proveedor"."nombre", "repositorio_proveedor"."pagina_web", "repositorio_proveedor"."estado", "repositorio_proveedor"."persona_id" FROM "repositorio_proveedor" WHERE "repositorio_proveedor"."id" = '36dc5377212d4615aaf64aabc52b25aa'; args=('36dc5377212d4615aaf64aabc52b25aa',)
[2017-11-08 20:37:31] DEBUG [django.db.backends:90] (0.000) SELECT "repositorio_unidad"."id", "repositorio_unidad"."marca", "repositorio_unidad"."placa", "repositorio_unidad"."color", "repositorio_unidad"."tipo_combustible", "repositorio_unidad"."ruedas", "repositorio_unidad"."altura", "repositorio_unidad"."ancho", "repositorio_unidad"."tipo", "repositorio_unidad"."cilindros", "repositorio_unidad"."ejes", "repositorio_unidad"."nro_motor", "repositorio_unidad"."km_recorrido", "repositorio_unidad"."ano_modelo", "repositorio_unidad"."asientos", "repositorio_unidad"."carga_util", "repositorio_unidad"."longitud", "repositorio_unidad"."nro_serie", "repositorio_unidad"."pasajeros", "repositorio_unidad"."peso_bruto", "repositorio_unidad"."peso_seco" FROM "repositorio_unidad" WHERE "repositorio_unidad"."id" = 'ea9f71d358304da8a078d262b40f239d'; args=('ea9f71d358304da8a078d262b40f239d',)
[2017-11-08 20:37:31] DEBUG [django.db.backends:90] (0.000) SELECT "repositorio_proveedor"."id", "repositorio_proveedor"."nombre", "repositorio_proveedor"."pagina_web", "repositorio_proveedor"."estado", "repositorio_proveedor"."persona_id" FROM "repositorio_proveedor" WHERE "repositorio_proveedor"."id" = '8616f1dfa07b442f91f870e83be9f577'; args=('8616f1dfa07b442f91f870e83be9f577',)
[2017-11-08 20:37:31] DEBUG [django.db.backends:90] (0.000) SELECT "repositorio_unidad"."id", "repositorio_unidad"."marca", "repositorio_unidad"."placa", "repositorio_unidad"."color", "repositorio_unidad"."tipo_combustible", "repositorio_unidad"."ruedas", "repositorio_unidad"."altura", "repositorio_unidad"."ancho", "repositorio_unidad"."tipo", "repositorio_unidad"."cilindros", "repositorio_unidad"."ejes", "repositorio_unidad"."nro_motor", "repositorio_unidad"."km_recorrido", "repositorio_unidad"."ano_modelo", "repositorio_unidad"."asientos", "repositorio_unidad"."carga_util", "repositorio_unidad"."longitud", "repositorio_unidad"."nro_serie", "repositorio_unidad"."pasajeros", "repositorio_unidad"."peso_bruto", "repositorio_unidad"."peso_seco" FROM "repositorio_unidad" WHERE "repositorio_unidad"."id" = 'ea9f71d358304da8a078d262b40f239d'; args=('ea9f71d358304da8a078d262b40f239d',)
[2017-11-08 20:37:31] INFO [django.server:131] "GET /api/repositorio/detalleUnidades/ HTTP/1.1" 200 668
[2017-11-08 20:37:49] DEBUG [django.db.backends:90] (0.004) SELECT "repositorio_unidad"."id", "repositorio_unidad"."marca", "repositorio_unidad"."placa", "repositorio_unidad"."color", "repositorio_unidad"."tipo_combustible", "repositorio_unidad"."ruedas", "repositorio_unidad"."altura", "repositorio_unidad"."ancho", "repositorio_unidad"."tipo", "repositorio_unidad"."cilindros", "repositorio_unidad"."ejes", "repositorio_unidad"."nro_motor", "repositorio_unidad"."km_recorrido", "repositorio_unidad"."ano_modelo", "repositorio_unidad"."asientos", "repositorio_unidad"."carga_util", "repositorio_unidad"."longitud", "repositorio_unidad"."nro_serie", "repositorio_unidad"."pasajeros", "repositorio_unidad"."peso_bruto", "repositorio_unidad"."peso_seco" FROM "repositorio_unidad" WHERE ("repositorio_unidad"."id" LIKE '%%' ESCAPE '\' OR "repositorio_unidad"."marca" LIKE '%%' ESCAPE '\'); args=('%%', '%%')
[2017-11-08 20:37:49] INFO [django.server:131] "GET /api/repositorio/unidades/ HTTP/1.1" 200 867
[2017-11-08 20:38:35] DEBUG [django.db.backends:90] (0.003) SELECT "repositorio_unidad"."id", "repositorio_unidad"."marca", "repositorio_unidad"."placa", "repositorio_unidad"."color", "repositorio_unidad"."tipo_combustible", "repositorio_unidad"."ruedas", "repositorio_unidad"."altura", "repositorio_unidad"."ancho", "repositorio_unidad"."tipo", "repositorio_unidad"."cilindros", "repositorio_unidad"."ejes", "repositorio_unidad"."nro_motor", "repositorio_unidad"."km_recorrido", "repositorio_unidad"."ano_modelo", "repositorio_unidad"."asientos", "repositorio_unidad"."carga_util", "repositorio_unidad"."longitud", "repositorio_unidad"."nro_serie", "repositorio_unidad"."pasajeros", "repositorio_unidad"."peso_bruto", "repositorio_unidad"."peso_seco" FROM "repositorio_unidad" WHERE ("repositorio_unidad"."id" LIKE '%%' ESCAPE '\' OR "repositorio_unidad"."marca" LIKE '%%' ESCAPE '\'); args=('%%', '%%')
[2017-11-08 20:38:35] INFO [django.server:131] "GET /api/repositorio/unidades/ HTTP/1.1" 200 867
[2017-11-08 20:38:45] DEBUG [django.db.backends:90] (0.003) SELECT "repositorio_cliente"."id", "repositorio_cliente"."descripcion", "repositorio_cliente"."fecha_creada", "repositorio_cliente"."fecha_actualizada", "repositorio_cliente"."estado", "repositorio_cliente"."persona_id" FROM "repositorio_cliente" WHERE ("repositorio_cliente"."id" LIKE '%%' ESCAPE '\' OR "repositorio_cliente"."descripcion" LIKE '%%' ESCAPE '\'); args=('%%', '%%')
[2017-11-08 20:38:45] DEBUG [django.db.backends:90] (0.000) SELECT "repositorio_persona"."id", "repositorio_persona"."nombre", "repositorio_persona"."ape_paterno", "repositorio_persona"."ape_materno", "repositorio_persona"."dni", "repositorio_persona"."ruc", "repositorio_persona"."celular", "repositorio_persona"."tipo_persona", "repositorio_persona"."direccion", "repositorio_persona"."departamento", "repositorio_persona"."provincia", "repositorio_persona"."distrito" FROM "repositorio_persona" WHERE "repositorio_persona"."id" = 'e1b96617c94342d595b1952204fbeba8'; args=('e1b96617c94342d595b1952204fbeba8',)
[2017-11-08 20:38:45] DEBUG [django.db.backends:90] (0.000) SELECT "repositorio_persona"."id", "repositorio_persona"."nombre", "repositorio_persona"."ape_paterno", "repositorio_persona"."ape_materno", "repositorio_persona"."dni", "repositorio_persona"."ruc", "repositorio_persona"."celular", "repositorio_persona"."tipo_persona", "repositorio_persona"."direccion", "repositorio_persona"."departamento", "repositorio_persona"."provincia", "repositorio_persona"."distrito" FROM "repositorio_persona" WHERE "repositorio_persona"."id" = 'eb0d78a6fd5c49da81399fc41cb844ff'; args=('eb0d78a6fd5c49da81399fc41cb844ff',)
[2017-11-08 20:38:45] INFO [django.server:131] "GET /api/repositorio/clientes/ HTTP/1.1" 200 511
[2017-11-08 20:53:50] DEBUG [django.db.backends:90] (0.004) SELECT "repositorio_unidad"."id", "repositorio_unidad"."marca", "repositorio_unidad"."placa", "repositorio_unidad"."color", "repositorio_unidad"."tipo_combustible", "repositorio_unidad"."ruedas", "repositorio_unidad"."altura", "repositorio_unidad"."ancho", "repositorio_unidad"."tipo", "repositorio_unidad"."cilindros", "repositorio_unidad"."ejes", "repositorio_unidad"."nro_motor", "repositorio_unidad"."km_recorrido", "repositorio_unidad"."ano_modelo", "repositorio_unidad"."asientos", "repositorio_unidad"."carga_util", "repositorio_unidad"."longitud", "repositorio_unidad"."nro_serie", "repositorio_unidad"."pasajeros", "repositorio_unidad"."peso_bruto", "repositorio_unidad"."peso_seco" FROM "repositorio_unidad" WHERE ("repositorio_unidad"."id" LIKE '%%' ESCAPE '\' OR "repositorio_unidad"."marca" LIKE '%%' ESCAPE '\'); args=('%%', '%%')
[2017-11-08 20:53:50] INFO [django.server:131] "GET /api/repositorio/unidades/ HTTP/1.1" 200 867
[2017-11-08 21:51:18] DEBUG [django.db.backends:90] (0.003) SELECT "repositorio_personal"."id", "repositorio_personal"."categoria", "repositorio_personal"."fecha_creada", "repositorio_personal"."fecha_actualizada", "repositorio_personal"."estado", "repositorio_personal"."persona_id" FROM "repositorio_personal" WHERE ("repositorio_personal"."id" LIKE '%%' ESCAPE '\' OR "repositorio_personal"."categoria" LIKE '%%' ESCAPE '\'); args=('%%', '%%')
[2017-11-08 21:51:18] DEBUG [django.db.backends:90] (0.000) SELECT "repositorio_persona"."id", "repositorio_persona"."nombre", "repositorio_persona"."ape_paterno", "repositorio_persona"."ape_materno", "repositorio_persona"."dni", "repositorio_persona"."ruc", "repositorio_persona"."celular", "repositorio_persona"."tipo_persona", "repositorio_persona"."direccion", "repositorio_persona"."departamento", "repositorio_persona"."provincia", "repositorio_persona"."distrito" FROM "repositorio_persona" WHERE "repositorio_persona"."id" = '71623f0d91804af1b4e6634c533812da'; args=('71623f0d91804af1b4e6634c533812da',)
[2017-11-08 21:51:18] DEBUG [django.db.backends:90] (0.000) SELECT "repositorio_persona"."id", "repositorio_persona"."nombre", "repositorio_persona"."ape_paterno", "repositorio_persona"."ape_materno", "repositorio_persona"."dni", "repositorio_persona"."ruc", "repositorio_persona"."celular", "repositorio_persona"."tipo_persona", "repositorio_persona"."direccion", "repositorio_persona"."departamento", "repositorio_persona"."provincia", "repositorio_persona"."distrito" FROM "repositorio_persona" WHERE "repositorio_persona"."id" = 'eb0d78a6fd5c49da81399fc41cb844ff'; args=('eb0d78a6fd5c49da81399fc41cb844ff',)
[2017-11-08 21:51:18] DEBUG [django.db.backends:90] (0.001) SELECT "repositorio_persona"."id", "repositorio_persona"."nombre", "repositorio_persona"."ape_paterno", "repositorio_persona"."ape_materno", "repositorio_persona"."dni", "repositorio_persona"."ruc", "repositorio_persona"."celular", "repositorio_persona"."tipo_persona", "repositorio_persona"."direccion", "repositorio_persona"."departamento", "repositorio_persona"."provincia", "repositorio_persona"."distrito" FROM "repositorio_persona" WHERE "repositorio_persona"."id" = '71623f0d91804af1b4e6634c533812da'; args=('71623f0d91804af1b4e6634c533812da',)
[2017-11-08 21:51:18] INFO [django.server:131] "GET /api/repositorio/personales/ HTTP/1.1" 200 741
